Create .gitkeep
avoid error due to missing dir
```
python3 src/data/make_dataset.py data/raw data/processed
Usage: make_dataset.py [OPTIONS] INPUT_FILEPATH OUTPUT_FILEPATH
Try "make_dataset.py --help" for help.

Error: Invalid value for "INPUT_FILEPATH": Path "data/raw" does not exist.
make: *** [data] Error 2
```